name: C++ CI (MSVC)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            submodules: 'true'

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up MSVC
        shell: cmd
        run: |
            "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      - name: Run Create Libraries batch file
        shell: cmd
        run: CreateProjectLibraries.bat

      - name: Run Generate Project script
        shell: cmd
        run: GenerateProjects.bat